# volumes:
#   node_modules: {}                      # ← declare it at top level
volumes:

services:
  web:
    build:
      dockerfile: web.Dockerfile 
    container_name: web 
    ports: 
      - "5173:5173" 
    # Use polling so file‐watch works reliably in containers
    environment: 
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    volumes:
      - ./web:/app # bind‐mount your source code
#      - node_modules:/app/node_modules  # mount a **named Docker volume** over that folder
      - /app/node_modules   
    command: > 
      sh -c " npm ci && npm run dev -- --mode docker"

  backend:
    env_file:
      - .env.dev 
    volumes:
      - ~/.ssh/ICT2216-student12.pem:/run/ssh/key.pem:ro


          
  wrk:
    build:
      context: tools/wrk
      dockerfile: wrk.dockerfile
    depends_on:
      - backend
    # Change -t, -c, -d or URL to suit your test
    command: ["-t2", "-c20", "-d30s", "--latency", "http://backend:5000/"]