services: 
  web: 
    build: 
      context: ./web 

  backend:
    build: 
      context: ./Backend
      dockerfile: backend.Dockerfile 
    container_name: backend 
    ports: 
      - "5000:5000"    
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase_key.json
    volumes:
      - ./connectit-63f60-firebase-adminsdk-fbsvc-c106a0e591.json:/app/firebase_key.json:ro

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  splunk:
      image: splunk/splunk:9.1.2
      container_name: splunk
      #ports:
      #  - "8000:8000" # Splunk web UI
      #  - "8088:8088" # HEC (HTTP Event Collector) endpoint
      env_file:
      - .env
      environment:
        # Accept Splunk license
        - SPLUNK_START_ARGS=--accept-license
        - SPLUNK_ENABLE_LISTEN=8088
        - SPLUNK_HEC_URL=https://splunk.connectitweb.site:443/services/collector
      volumes:
        - splunk_data:/opt/splunk/var/lib/splunk # Persistent storage for Splunk data
        - splunk_etc:/opt/splunk/etc # Persistent storage for Splunk configurations
        - ./splunk-config.conf:/opt/splunk/etc/system/local/web.conf
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8000/en-US/account/login || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 5
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
volumes:
  redis-data:
  splunk_data: {} # Volume for Splunk data persistence
  splunk_etc: {} # Volume for Splunk Configurations persistence



