services: 
  web: 
    build: 
      context: ./web 

  backend:
    build: 
      context: ./Backend
      dockerfile: backend.Dockerfile 
    container_name: backend 
    ports: 
      - "5000:5000"    
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase_key.json
    volumes:
      - ./connectit-63f60-firebase-adminsdk-fbsvc-c106a0e591.json:/app/firebase_key.json:ro

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    


