services:
  backend:
    depends_on:
      - sql-prod
    env_file:
      - .env.prod

  sql-dev:
    image: mysql:8.0
    container_name: sql-dev
    env_file:
      - .env   
    ports:
      - "3307:3306"
    volumes:
      - ./sql_data_dev:/var/lib/mysql

  sql-prod:
    image: mysql:8.0
    container_name: sql-prod
    env_file:
      - .env.prod
    ports:
      - "3306:3306"
    volumes:
      - ./sql_data_prod:/var/lib/mysql


  web:
    build:
      context: ./web
      dockerfile: webProd.Dockerfile
      args:
        VITE_HCAPTCHA_SITEKEY: ${VITE_HCAPTCHA_SITEKEY}
    container_name: web-prod
    expose:
      - "3300"
    env_file:
      - .env
    depends_on:
      - backend
    volumes: []
    command: []
    restart: unless-stopped


  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-startup.sh:/nginx-startup.sh
      #- ./nginx-reverse-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl  # Mount entire ssl directory
      - ./certbot-www:/var/www/certbot # this is for the cert bot to do the challenge 
    depends_on:
      - web
    restart: unless-stopped
    command : ["/bin/sh", "/nginx-startup.sh"]



  certbot:
    image: certbot/certbot
    container_name: certbot
    profiles: ["ssl"]
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./certbot-www:/var/www/certbot
    entrypoint:
      - sh
      - -c
      - |
        certbot certonly \
          --webroot -w /var/www/certbot \
          --email cheahzhengfeng@gmail.com \
          --agree-tos --no-eff-email \
          --rsa-key-size 4096 \
          --expand \
          --force-renewal \
          -d connectitweb.site -d www.connectitweb.site -d splunk.connectitweb.site

  splunk:
      image: splunk/splunk:9.1.2
      container_name: splunk
      #ports:
      #  - "8000:8000" # Splunk web UI
      #  - "8088:8088" # HEC (HTTP Event Collector) endpoint
      env_file:
      - .env.prod
      environment:
        # Accept Splunk license
        - SPLUNK_START_ARGS=--accept-license
        - SPLUNK_ENABLE_LISTEN=8088
        - SPLUNK_HEC_URL=https://splunk.connectitweb.site:443/services/collector
        - SPLUNK_HTTP_ENABLESSL=false
      volumes:
        - splunk_data:/opt/splunk/var/lib/splunk # Persistent storage for Splunk data
        - splunk_etc:/opt/splunk/etc # Persistent storage for Splunk configurations
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8000/en-US/account/login || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 5
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
volumes:
  splunk_data: {} # Volume for Splunk data persistence
  splunk_etc: {} # Volume for Splunk Configurations persistence