services: 
  web: 
    build: 
      context: ./web 

  backend:
    build: 
      context: ./Backend
      dockerfile: backend.Dockerfile 
    container_name: backend 
    ports: 
      - "5000:5000"    
    env_file:
      - .env

    


