volumes:
  node_modules: {}                      # ← declare it at top level
  
services: 
  web: 
    build: 
      context: ./web 
      dockerfile: web.Dockerfile 
    container_name: web 
    ports: 
      - "5173:5173" 
    # Use polling so file‐watch works reliably in containers
    environment: 
      - CHOKIDAR_USEPolling=true 
    # command: ["npm","run","dev","--","--mode","docker"]
    volumes:
      - ./web:/app # bind‐mount your source code
      - node_modules:/app/node_modules  # mount a **named Docker volume** over that folder
    command: > 
      sh -c "npm ci && npm run dev -- --mode docker"
  backend:
    build: 
      context: ./Backend
      dockerfile: backend.Dockerfile 
    container_name: backend 
    ports: 
      - "5000:5000" 
    environment: 
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - FLASK_DEBUG=${FLASK_DEBUG} 
    
  sql: 
    image: mysql:8.0
    container_name: sql 
    restart: always 
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} 
    ports: 
      - "3307:3306"
    volumes: 
      - ./sql_data:/var/lib/mysql 


