# volumes:
#   node_modules: {}                      # ← declare it at top level
  
services:
  web:
    build:
      dockerfile: web.Dockerfile 
    container_name: web 
    ports: 
      - "5173:5173" 
    # Use polling so file‐watch works reliably in containers
    environment: 
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    volumes:
      - ./web:/app # bind‐mount your source code
#      - node_modules:/app/node_modules  # mount a **named Docker volume** over that folder
      - /app/node_modules   
    command: > 
      sh -c " npm ci && npm run dev -- --mode docker"

  backend:
    env_file:
      - .env.dev 
    volumes:
      - ~/.ssh/ICT2216-student12.pem:/run/ssh/key.pem:ro
      - ./connectit-63f60-firebase-adminsdk-fbsvc-c106a0e591.json:/app/firebase_key.json:ro
    
    environment: 
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase_key.json 
