services:
  backend:
    env_file:
      - .env.prod

  sql-dev:
    image: mysql:8.0
    container_name: sql-dev
    env_file:
      - .env      
    ports:
      - "3307:3306"
    volumes:
      - ./sql_data_dev:/var/lib/mysql

  sql-prod:
    image: mysql:8.0
    container_name: sql-prod
    env_file:
      - .env.prod
    ports:
      - "3306:3306"
    volumes:
      - ./sql_data_prod:/var/lib/mysql