# volumes:
#   node_modules: {}                      # ← declare it at top level
volumes:
  splunk_data: {} # Volume for Splunk data persistence

services:
  web:
    build:
      dockerfile: web.Dockerfile 
    container_name: web 
    ports: 
      - "5173:5173" 
    # Use polling so file‐watch works reliably in containers
    environment: 
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    volumes:
      - ./web:/app # bind‐mount your source code
#      - node_modules:/app/node_modules  # mount a **named Docker volume** over that folder
      - /app/node_modules   
    command: > 
      sh -c " npm ci && npm run dev -- --mode docker"

  backend:
    env_file:
      - .env.dev 
    volumes:
      - ~/.ssh/ICT2216-student12.pem:/run/ssh/key.pem:ro
      - ./logs:/var/log
      

  
  splunk:
      image: splunk/splunk:latest
      container_name: splunk
      ports:
        - "8000:8000" # Splunk web UI
        - "8088:8088" # HEC (HTTP Event Collector) endpoint
      env_file:
      - .env.dev
      environment:
        # Accept Splunk license
        - SPLUNK_START_ARGS=--accept-license
        - SPLUNK_ENABLE_LISTEN=8088
      volumes:
        - splunk_data:/opt/splunk/var/lib/splunk # Persistent storage for Splunk data
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8000/en-US/account/login || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 5
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
