services: 
  web: 
    build: 
      context: ./web 
      dockerfile: webProd.Dockerfile 
      args:
        VITE_HCAPTCHA_SITEKEY: ${VITE_HCAPTCHA_SITEKEY} 
    image: zfcrow/connectit:web-latest
    container_name: web-prod 
    ports:
      - "3300:3300" 
    env_file: 
      - .env
    depends_on: 
      - backend 
    restart: unless-stopped


  backend:
    build: 
      context: ./Backend
      dockerfile: backend.Dockerfile 
    image: zfcrow/connectit:backend-latest
    container_name: backend 
    ports: 
      - "5000:5000"    
    env_file:
      - .env
      - .env.dev
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase_key.json
      - SPLUNK_HEC_URL=https://splunk:8088/services/collector/event
    volumes:
      - ./connectit-63f60-firebase-adminsdk-fbsvc-c106a0e591.json:/app/firebase_key.json:ro
      - ~/.ssh/ICT2216-student12.pem:/run/ssh/key.pem:ro


  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # wrk:
  #   build:
  #     context: tools/wrk
  #     dockerfile: wrk.dockerfile
  #   depends_on:
  #     - backend
  #   # Change -t, -c, -d or URL to suit your test
  #   command: ["-t2", "-c20", "-d30s", "--latency", "http://backend:5000/"]


volumes:
  redis-data:



