volumes:
  node_modules: {}                      # ← declare it at top level
  
services: 
  web: 
    build: 
      context: ./web 
      dockerfile: web.Dockerfile 
    container_name: web 
    ports: 
      - "5173:5173" 
    # Use polling so file‐watch works reliably in containers
    environment: 
      - CHOKIDAR_USEPOLLING=true
    # command: ["npm","run","dev","--","--mode","docker"]
    volumes:
      - ./web:/app # bind‐mount your source code
      - node_modules:/app/node_modules  # mount a **named Docker volume** over that folder
    command: > 
      sh -c "npm run dev -- --mode docker"

  backend:
    build: 
      context: ./Backend
      dockerfile: backend.Dockerfile 
    container_name: backend 
    ports: 
      - "5000:5000"
    env_file: 
      - .env     

    


