import type { JobListing } from "../../type/jobListing";
export const sampleJobs: JobListing[] = [
  {
    jobId: 1,
    companyId: 2,
    companyName: "Tech Solutions",
    companyAddress: "123 Tech Lane, Silicon Valley, CA",
    title: "Frontend Developer",
    workArrangement: "Remote",
    description:
      "Build and maintain user interfaces using React. Collaborate with designers and backend engineers to implement responsive web designs, optimize performance, and ensure accessibility. Mentor junior developers and conduct code reviews to uphold best practices across our frontend codebase.",
    applicationDeadline: "2024-07-01T00:00:00Z",
    minSalary: 4000,
    maxSalary: 6000,
    type: "Full-Time",
    createdAt: "2024-05-24T09:00:00Z",
    responsibilities: [
      "Develop new user-facing features",
      "Ensure the technical feasibility of UI/UX designs",
      "Optimize application for maximum speed and scalability",
      "Collaborate with other team members and stakeholders",
    ],
    field: "Software Development",
    yearsOfExperience: 3,
  },
  {
    jobId: 2,
    companyId: 102,
    companyName: "Data Corp",
    companyAddress: "456 Data St, New York, NY",
    title: "Backend Engineer",
    workArrangement: "Hybrid",
    description:
      "As a Backend Engineer on our team, you will take ownership of designing and implementing robust, high-performance APIs that serve as the backbone of our platform. You’ll architect RESTful and/or GraphQL endpoints using Node.js, Python, or Go, ensuring they can handle thousands of concurrent requests with low latency. Working in a cloud-native environment (AWS, Azure, or GCP), you’ll provision and manage infrastructure—leveraging services like EC2/Lambda, Kubernetes/EKS, RDS/DynamoDB, and Redis—while treating everything as code through tools such as Terraform or CloudFormation. You will also implement monitoring, logging, and alerting to maintain SLAs and participate in on-call rotations to triage and debug production issues.",
    applicationDeadline: "2024-07-15T00:00:00Z",
    minSalary: 4500,
    maxSalary: 7000,
    type: "Contract",
    createdAt: "2024-05-20T09:00:00Z",
    responsibilities: [
      "Design and implement scalable APIs",
      "Optimize database queries and schema",
      "Ensure security and data protection",
    ],
    field: "Software Development",
    yearsOfExperience: 2,
  },
  {
    jobId: 3,
    companyId: 103,
    companyName: "GreenEnergy Inc.",
    companyAddress: "789 Renewable Ave, Berlin, Germany",
    title: "DevOps Engineer",
    workArrangement: "Office",
    description:
      "Design, implement, and maintain CI/CD pipelines, automate infrastructure provisioning, and ensure high availability of our cloud services. Partner with development teams to facilitate smooth deployments, optimize build times, and reduce manual intervention.",
    applicationDeadline: "2024-08-01T00:00:00Z",
    minSalary: 5000,
    maxSalary: 8000,
    type: "Full-Time",
    createdAt: "2024-05-18T14:30:00Z",
    responsibilities: [
      "Automate deployment processes",
      "Monitor system performance and reliability",
      "Implement security best practices",
    ],
    field: "DevOps",
    yearsOfExperience: 3,
  },
  {
    jobId: 4,
    companyId: 104,
    companyName: "FinTech Labs",
    companyAddress: "101 Finance Blvd, London, UK",
    title: "Data Scientist",
    workArrangement: "Remote",
    description:
      "Develop predictive models and machine learning algorithms to drive customer insights and risk analytics. Process large datasets using Spark and Hadoop, clean and transform data, and communicate findings through interactive dashboards.",
    applicationDeadline: "2024-07-20T00:00:00Z",
    minSalary: 6000,
    maxSalary: 9000,
    type: "Full-Time",
    createdAt: "2024-05-22T11:15:00Z",
    responsibilities: [
      "Analyze large datasets to extract insights",
      "Build and deploy machine learning models",
      "Collaborate with cross-functional teams to implement data-driven solutions",
    ],
    field: "Data Science",
    yearsOfExperience: 2,
  },
  {
    jobId: 5,
    companyId: 105,
    companyName: "HealthTech Solutions",
    companyAddress: "202 Medical Way, Singapore",
    title: "UX/UI Designer Intern",
    workArrangement: "Hybrid",
    description:
      "Join our UX team as an intern and assist in user research, wireframing, prototyping, and usability testing for our healthcare platform. You’ll work closely with product managers and engineers to iterate on designs, gather feedback from stakeholders, and contribute to a seamless, accessible user experience that helps patients and providers connect more effectively.",
    applicationDeadline: "2024-06-30T00:00:00Z",
    minSalary: 2000,
    maxSalary: 3000,
    type: "Internship",
    createdAt: "2024-05-25T10:00:00Z",
    responsibilities: [
      "Conduct user research and usability testing",
      "Create wireframes and prototypes",
      "Collaborate with developers to implement designs",
    ],
    field: "Design",
    yearsOfExperience: 0,
  },
];
