# .github/workflows/dependency-check.yml
name: OWASP Dependency Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install project dependencies
        working-directory: web
        run: npm ci

      - name: Dependency Check (Node project)
        uses: dependency-check/Dependency-Check_Action@v1 # uses the newer inputs
        with:
          project: "ConnectIt" # Project name inside the report
          path: "web" # Directory to scan (package.json / lockfile)
          format: "HTML" # Report format(s) – comma-sep for multiple
          out: "dependency-check-report" # Where to put the report(s)
          args: > # Extra CLI flags
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
            --disableYarn

      # 4️⃣  Upload the HTML report as a build artifact
      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report # matches the `out:` folder above
