# .github/workflows/deploy.yml 


name: Deploy to Production 

on: 
  workflow_run:
    workflows: ["OWASP Dependency Check"]
    types:
      - completed 

jobs: 
  deploy: 
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: start SSH agent 
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }} # Your SSH private key stored in GitHub Secrets 

      - name: Add EC2 to known hosts 
        run: | 
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts 
      

      - name: Sync full ConnectIT directory to EC2
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./${{ github.workspace ## strip leading slash if needed }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/ConnectIT/
    